apiVersion: skaffold/v2alpha4
kind: Config
metadata:
  name: stage
build:
  artifacts:
  - image: irony/stage
    sync:
      infer:
      - 'index.html'
      - 'src/**/*.js'
deploy:
  kubectl:
    manifests:
    - k8s/stage-service.yaml
    - k8s/ghost-ingress.yaml
