apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: "true"
  generation: 1
  labels:
    app: samtal-ghost
  name: samtal-ghost
  namespace: default
spec:
  rules:
  - host: samtal.io
    http:
      paths:
      - backend:
          serviceName: samtal-ghost
          servicePort: http
        path: /
  tls:
  - hosts:
    - samtal.io
    secretName: samtal-ghost-prod-tls
status:
  loadBalancer: {}
