apiVersion: v1
kind: Service
metadata:
  name: city
spec:
  ports:
  - port: 8000
  type: LoadBalancer
  selector:
    app: city
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: city
spec:
  selector:
    matchLabels:
      app: city
  template:
    metadata:
      labels:
        app: city
    spec:
      containers:
      - name: city
        image: irony/stage
        ports:
        - containerPort: 8000
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: city-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - city.vrmeet.io
    secretName: city-prod-tls
  rules:
  - host: city.vrmeet.io
    http:
      paths:
      - backend:
          serviceName: city
          servicePort: 8000